### ISSUE TITLE
Add handwired project

### ISSUE THREAD

**Issue by nahuel** [pashutk/Cherry_MX_ULP#1]
Add thiis handwired project to the README, is a great non-SMD-PCB alternative for mounting and soldering the ULP switches (see images in second comment link):

- https://www.reddit.com/r/ErgoMechKeyboards/comments/18qr1xp/cherry_ulp_prototyping/
- https://www.reddit.com/r/ErgoMechKeyboards/comments/18qr1xp/cherry_ulp_prototyping/kez1e7f/

**Comment by pashutk** [comment]
Done! https://github.com/pashutk/Cherry_MX_ULP/commit/ac65a5b789917aae82f199629806ff953a9780a7

Thanks for sharing @nahuel thats some unique approach here. Please keep going!

**Comment by nahuel** [comment]
Note that this is not my project, only a random one I found on reddit, please remove my name from the Readme :)

**Comment by pashutk** [comment]
Oh thanks for pointing out, will change it for an appropriate mention!
