### ISSUE TITLE
Add Dactyl Manuform with Cherry ULP to projects

### ISSUE THREAD

**Issue by nahuel** [pashutk/Cherry_MX_ULP#2]
Link: https://www.reddit.com/r/ErgoMechKeyboards/comments/18nxvd9/dactyl_manuform_with_cherry_ultra_low_profile/

**Comment by nahuel** [comment]
Also: https://github.com/jonboh/ulp-dactyl  and https://github.com/jonboh/amoeba-cherry-ulp

**Comment by pashutk** [comment]
This is ongoing work: https://github.com/pashutk/Cherry_MX_ULP/pull/3

Huge thanks for the suggestion! Please come back with more :)

I'm closing the issue since we already have a PR for it
