### ISSUE TITLE
KeyPulse Elite -- new keyboard

### ISSUE THREAD

**Issue by bakirov** [pashutk/Cherry_MX_ULP#7]
Hi, there is a new keyboard on Kickstarter that uses CHERRY MX ULP Switches: KeyPulse Elite, Ultra-Slim 65% Mechanical Keyboard: https://www.kickstarter.com/projects/1658898886/keypulse-elite-slim-mechanical-keyboards/description

**Comment by pashutk** [comment]
Hi there,
It's definitely a rebranding of the Mistal's Air One with added BT/Radio. The frame, layout and keycaps are the same. Really nice of them to make a wireless version, anyway, that was definitely a missing part of the Air One.
Added https://github.com/pashutk/Cherry_MX_ULP/commit/6f5dbe67db446530b7c0fedd6b27f51040a013dd
Thank you for your contribution!
